#use_frameworks!

platform :ios, '9.0'

target 'JQLogUtil_Example' do
  pod 'JQLogUtil', :path => '../', :subspecs => ['Core', 'DevTool']

  target 'JQLogUtil_Tests' do
    inherit! :search_paths

    
  end
end
